### ISSUE TITLE
the Chinese characters were garbled （中文乱码问题）

### ISSUE THREAD

**Issue by Lsx1131188021** [jonas-haeusler/jasypt-maven-plugin#34]
First of all, thank Daniel for his open source contribution.
    When I use "jasypt: encrypt" to encrypt an application. yml configuration file, some Chinese comments in the file will become garbled. It is strange that not all Chinese characters are garbled, but a few Chinese characters. I try to set "- Dfile. encoding=UTF-8", or adjust the command line encoding to UTF-8. 
    It is hoped that after encrypting the output, it can support coding custom configuration. Of course, this does not affect the normal use of functions.
    I use Windows OS.

中文：
    首先，非常感谢大牛的开源贡献。
    当我使用“jasypt:encrypt”加密一个application.yml配置文件时，文件中的部分中文注释会变成乱码。很奇怪的是，并不是所有的中文都出现乱码，而是少部分中文。我尝试设置“-Dfile.encoding=UTF-8”，或者将命令行编码调整为UTF-8都不生效。希望能在加密输出后，支持编码自定义配置。当然了，这并不影响正常的功能使用。
    我使用的是windows OS。

**Comment by jonas-haeusler** [comment]
hi @Lsx1131188021
> When I use "jasypt: encrypt" to encrypt an application. yml configuration file

this project is for `.properties` files, not for `.yaml` files.
Did you confuse it with https://github.com/ulisesbocchio/jasypt-spring-boot?

feel free to reopen is this is not the case.
